### ISSUE TITLE
to-do 5/12/16

### ISSUE THREAD

**Issue by allisonlu** [RadBitt/HIV-Timeline#5]
- [x] add blurbs to community partners
- [x] add links on testing page
- [x] add external links on aboutHIV
- [x] align brochures on prevention page
- [x] links for community partners
- [x] links on advocacy page
